// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHCSOriboQAmHqOwoo-4t3ucDXOFPFBw',
    appId: '1:996996908836:web:001207a96e889d7fb115b1',
    messagingSenderId: '996996908836',
    projectId: 'chatterbox-fa4ed',
    authDomain: 'chatterbox-fa4ed.firebaseapp.com',
    storageBucket: 'chatterbox-fa4ed.appspot.com',
    measurementId: 'G-02K1508H1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6TC2EVbaz_lfDILtrIqR_sxgmPAldX7w',
    appId: '1:996996908836:android:b68735fd3ab986e4b115b1',
    messagingSenderId: '996996908836',
    projectId: 'chatterbox-fa4ed',
    storageBucket: 'chatterbox-fa4ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEn6PEVQRGciKcFQFxpeOlZcz6BHrzyHg',
    appId: '1:996996908836:ios:88b27741c1db094eb115b1',
    messagingSenderId: '996996908836',
    projectId: 'chatterbox-fa4ed',
    storageBucket: 'chatterbox-fa4ed.appspot.com',
    iosBundleId: 'com.example.chatterBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmHCSOriboQAmHqOwoo-4t3ucDXOFPFBw',
    appId: '1:996996908836:web:2d354c79fd4dca17b115b1',
    messagingSenderId: '996996908836',
    projectId: 'chatterbox-fa4ed',
    authDomain: 'chatterbox-fa4ed.firebaseapp.com',
    storageBucket: 'chatterbox-fa4ed.appspot.com',
    measurementId: 'G-DV8Z7EQE1N',
  );
}
